### ISSUE TITLE
QA: production ECL creds into the workflow with GH Secrets and sed them into the .env file before building dspback

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspback#118]
https://test-ecl.earthchem.org is behind a firewall
Peng has okayed creating records on production ECL for a particular ORCID account (he is going to automate clearing records for this one account).

Can we target https://ecl.earthchem.org instead of https://test-ecl.earthchem.org and staging in our [default .env](https://github.com/cznethub/dspback/blob/develop/.env#L51) so that local builds (for my purposes via GH workflow) will be able to verify submission?

If no, I will disable these tests when run via GH workflow

**Comment by cbcunc** [comment]
@devincowan Is it OK that dsp-test continues targeting HS beta and Zenodo sandbox?

**Comment by sblack-usu** [comment]
I'm ok with this as long as the client-id and client-secret aren't the same as the production config.  It will still generate noise in production ecl and anyone running a local build would be pointing to production ecl.  If Peng wants to go this direction, it is fine, but there is going to be more garbage generated than just your user.  You could trace the test submission by client id if he wanted to clean it up.

From my perspective, either updating the firewall or if we can't modify the firewall, disabling the tests.  I don't like the idea of pointing to production repositories in our default config.

**Comment by devincowan** [comment]
@cbcunc yes, I was thinking just ECL. But...
@sblack-usu okay, I'm fine with detecting when tests are run via GH and disabling ECL repo checks in that case

**Comment by Maurier** [comment]
I rather we do not target production on any development setup. Firewall modification would be my suggestion as well.

**Comment by cbcunc** [comment]
There's a problem modifying test-ecl firewall for GH, as I understand it. No guaranteed IP range is there?

**Comment by cbcunc** [comment]
Plus, I misread to start with. We are talking about local builds and not dsp-test, correct? So you would be running GH workflows on local builds? All local builds? What about dsp-test?

**Comment by sblack-usu** [comment]
The github action is spinning up the local development configuration and testing against that.

**Comment by cbcunc** [comment]
Ah, "local build" in a GH action. Goodness. So what you really need is an .env for GH actions and leave the default .env checked into dspback alone? Because we really don't want to be checking *any* real credentials into a GH repo, save for possibly the *local* development (not a .env for a GH action) that's already there. My understanding is you have this in a GH secret not anyway, correct?

**Comment by devincowan** [comment]
yep right now users/passwords to run the QA tests are stored in GH Secrets
but Scott is right, the workflow just builds off of the default dspback [.env](https://github.com/cznethub/dspback/blob/develop/.env#L51)

I'm fine with just disabling the ECL tests that actually navigate to the repo and ensure the submission made it. There are only 2 of them at this point (though I had planned to build that coverage)

**Comment by sblack-usu** [comment]
We have been checking in credentials for the testing environments of the repositories.  That makes it easy for a local build to get running.  Otherwise developers would have to manage their own credentials or we would have to figure out another way to share the default testing credentials.

**Comment by cbcunc** [comment]
@devincowan Check this out: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses. It has a warning that the ranges are subject to change and to "regularly" check the meta API endpoint for changes.

**Comment by devincowan** [comment]
Yep, @cbcunc I saw that yesterday. Main reason I created this issue! Thanks...

**Comment by cbcunc** [comment]
@sblack-usu Right. I don't have any problem with test credentials for local environments as that's water under the bridge. But we are now talking about GH actions build and checking in production system creds. My question is, can't the GH workflow use GH secrets to get the .env it needs and leave the .env for local (not GH actions builds) alone?

**Comment by devincowan** [comment]
I can get the production ECL creds into the workflow with GH Secrets and sed them into the .env file before building dspback

**Comment by cbcunc** [comment]
Perfect. I would keep the tests and fix your workflow to run them as you need.

**Comment by devincowan** [comment]
thanks for the help all

**Comment by devincowan** [comment]
I base64 encoded an .env file with production ECL parameters (and sandbox for all others) as suggested [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-base64-binary-blobs-as-secrets) and added that to GH Secrets. Then base64 decode in the workflow to get a usable .env. Works great!

EXCEPT:
I hadn't thought about the fact that if I build dspback targeting prod ECL from within a GH workflow, _**we have to request whitelist to production ECL api to accept that connect**_... which seems like it is going to be every bit as intractable as trying to whitelist GH ip ranges on ecl-test

**Comment by sblack-usu** [comment]
>I hadn't thought about the fact that if I build dspback targeting prod ECL from within a GH workflow, we have to request whitelist to production ECL api to accept that connect... which seems like it is going to be every bit as intractable as trying to whitelist GH ip ranges on ecl-test

I thought that was only a non-production thing for ECL but I could be wrong.  Is Peng on Github?  I'll send him this issue and ask for his github id.

**Comment by devincowan** [comment]
Thanks @sblack-usu I guess I assumed it was also true for production but I can test and see if that's the case.
Don't think Peng is on GH? Not sure

**Comment by sparkji** [comment]
There is no firewall behind both ECL Staging and Production APIs. You don't need to request whitelist for APIs(staging and production). The firewall is set for ECL Staging application(test-ecl.earthchem.org) hosted in Lamont. Hope this answers your question.

**Comment by devincowan** [comment]
Scott and I discussed and decided these kind of tests that basically scrape the submission repo to ensure that nothing was lost in translation between dsp and the repro _are beyond the scope_ of our DSP testing. So I'm going to disable these tests when run against a local build (including via GH workflow). Thanks all!
