### ISSUE TITLE
Cannot delete submission on portal if submission already deleted in repository

### ISSUE THREAD

**Issue by cbcunc** [cznethub/dspback#51]
**Description of the bug**
I cannot delete submission on portal if submission already deleted in repository.

Steps to reproduce the bug:
1. Create submission in dsp
2. View in repository and delete from repository
3. View My Submissions in dsp and attempt to delete
4. See error "Failed to delete submission."
5. Refresh My Submissions and the submission is still there.

**Expected behavior**
1. Possibly a warning that the submission did not exist in the repository and the delete from My Submissions
2. Possibly provide an action to clean up My Submissions, checking to see what submissions no longer exist in repositories.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by sblack-usu** [comment]
There are 3 scenarios where a delete on the repository will fail.
1. As outlined in the description, the submission is already deleted in the repository
2. The submission is published and cannot be deleted
3. The user attempting to delete the submission does not have the necessary permissions to delete within the repository

**Comment by sblack-usu** [comment]
I can flip the logic in the code to first delete the submission in our db before attempting to delete the submission in the repository.  This would be the simplest approach on my end.  If the response from the repository were an unexpected response, then the repository error message and status code would be returned.  

The potential issues I see with this approach is that messaging on the frontend could be difficult especially when considering that different repositories might have different status codes and error messages.  Perhaps we should not be relaying the status code and text from the repositories as our response.  Instead we could look for these responses, log the responses, and then fit them into our own responses that would be standard across all repositories.  That way the frontend or users of our API would not have to deal with different status/text across different repositories.
